name:"rnet"
platform: "tensorrt_plan"
max_batch_size: 4096
input [
  {
    name: "input_1"
    data_type: TYPE_FP32
    dims: [24, 24, 3]
  }
]

output [
  {
    name: "conv5-2"
    data_type: TYPE_FP32
    dims: [ 4 ]
  },

  {
    name: "conv5-1"
    data_type: TYPE_FP32
    dims: [ 2 ]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [ 0 ]
  },
  {
    count: 2
    kind: KIND_GPU
    gpus: [ 1 ]
  }
]

