name: "onet_tf"
platform: "tensorflow_graphdef"
max_batch_size: 256
input [
  {
    name: "input_1"
    data_type: TYPE_FP32
    dims: [48, 48, 3]
  }
]

output [
  {
    name: "output_1"
    data_type: TYPE_FP32
    dims: [10]
  },

  {
    name: "output_2"
    data_type: TYPE_FP32
    dims: [4]
  },

  {
    name: "output_3"
    data_type: TYPE_FP32
    dims: [2]
  }
]

